services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/simple_bank
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_bank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  test:
    build: .
    entrypoint: /bin/sh -c "coverage run --source='.' manage.py test --verbosity=2 && coverage report"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/simple_bank
    depends_on:
      - db

volumes:
  postgres_data:
